# Generated by Django 4.1 on 2022-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.PositiveIntegerField(blank=True, choices=[(1, 'Lista'), (2, 'Bote')], null=True, verbose_name='Modo')),
                ('topeBola', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tope para Bola')),
                ('topeParlet', models.PositiveIntegerField(blank=True, verbose_name='Tope para parlet')),
                ('topeCentena', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tope para centena')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burto', models.PositiveIntegerField(verbose_name='Bruto')),
                ('limpio', models.PositiveIntegerField(verbose_name='Limpio')),
                ('premio', models.PositiveIntegerField(verbose_name='Premio')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha del tiro')),
                ('horario', models.CharField(choices=[('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10, verbose_name='Horario del tiro')),
            ],
            options={
                'verbose_name': 'Contabilidad',
                'verbose_name_plural': 'Contabilidad',
                'db_table': 'Contabilidad',
            },
        ),
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Fijo'), (2, 'Corrido'), (3, 'Parlet'), (4, 'Centena')], verbose_name='Tipo de jugada')),
                ('apostado', models.PositiveIntegerField(verbose_name='Apostado a la jugada')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de la jugada')),
                ('parlet', models.TextField(blank=True, default='{}', null=True)),
                ('esValida', models.BooleanField(default=True, verbose_name='Jugada valida')),
            ],
            options={
                'verbose_name': 'Jugada',
                'verbose_name_plural': 'Jugadas',
                'db_table': 'Jugada',
            },
        ),
        migrations.CreateModel(
            name='Limitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero limitado')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Fijo'), (2, 'Corrido'), (3, 'Parlet'), (4, 'Centena')], verbose_name='Para que tipo de jugada')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio para el premio')),
            ],
            options={
                'verbose_name': 'Limitado',
                'verbose_name_plural': 'Limitados',
                'db_table': 'Limitado',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de la jugada')),
            ],
            options={
                'verbose_name': 'Logs',
                'verbose_name_plural': 'Logs',
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Tiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNumero', models.PositiveIntegerField(verbose_name='Primer numero')),
                ('fijoCorrido', models.PositiveIntegerField(verbose_name='Primer numero fijo corrido')),
                ('primerCorrido', models.PositiveIntegerField(verbose_name='Primer numero corrido')),
                ('segundoCorrido', models.PositiveIntegerField(verbose_name='Segundo numero corrido')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha del tiro')),
                ('horario', models.CharField(choices=[('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10, verbose_name='Horario del tiro')),
            ],
            options={
                'verbose_name': 'Tiro',
                'verbose_name_plural': 'Tiros',
                'db_table': 'Tiro',
            },
        ),
    ]
