# Generated by Django 4.1 on 2022-09-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugada_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Persona que entra la jugada'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Persona que entra la jugada'),
        ),
    ]
