# Generated by Django 4.1 on 2022-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charada', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitado',
            name='numero',
            field=models.CharField(max_length=7, verbose_name='Numero limitado'),
        ),
    ]
