# Generated by Django 4.1 on 2022-10-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charada', '0003_alter_limitado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugada',
            name='parlet',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
