# Generated by Django 4.1 on 2022-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charada', '0005_rename_burto_contabilidad_bruto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidad',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del tiro'),
        ),
    ]
