# Generated by Django 4.1 on 2022-10-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charada', '0006_alter_contabilidad_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugada',
            old_name='esValida',
            new_name='esGanadora',
        ),
        migrations.AddField(
            model_name='jugada',
            name='premio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Premio'),
        ),
    ]
